**Autor** : Seu nome

**e-mail**: seu.email@semantix.com

#  <a name="resumo"> RESUMO </a>

Este notebook tem o objetivo de apresentar a biblioteca **pandas** e seu uso para manipulação e análise de dados. A pandas oferece estruturas e operações para manipular tabelas numéricas e séries temporais. É uma biblioteca relativamente rápida e bem flexivel.

#  <a name="indice">  Índice </a>

* [Resumo](#resumo)
* [Índice](#indice)
* [Seção 1 - Series e DataFrames](#secao_1)
* [Seção 2 - Funcionalidades Básicas](#secao_2)
* [Seção 3 - Indexação](#secao_3)
* [Seção 4 - Leitura e Escrita em arquivos](#secao_4)
* [Seção 5 - Algumas Dicas](#secao_5)
* [Conclusão](#conclusao)

#  <a name="secao_1"> Seção 1 - Series e DataFrames</a>
[Voltar ao índice](#indice)

Ref: https://pandas.pydata.org/

In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.2.4'

In [4]:
pd.Series([1,2,3,4], index= ['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
df = pd.DataFrame([[1,2,3],[4,5,6]],columns=['Coluna 1','Coluna 2','Coluna 3'], index=['a','b'])

In [6]:
type(df['Coluna 1'])

pandas.core.series.Series

In [7]:
type(df)

pandas.core.frame.DataFrame

#  <a name="secao_2"> Seção 2 - Funcionalidades Básicas</a>
[Voltar ao índice](#indice)

In [8]:
from numpy.random import randint

dados = [randint(10,size=3) for a in range(20)]

df = pd.DataFrame(dados,columns=['Coluna 1','Coluna 2','Coluna 3'])

In [9]:
df.head(2)

   Coluna 1  Coluna 2  Coluna 3
0         7         7         7
1         1         7         2

In [10]:
df.tail(7)

    Coluna 1  Coluna 2  Coluna 3
13         8         1         2
14         9         2         9
15         6         8         0
16         7         2         5
17         2         2         6
18         6         2         6
19         8         3         1

In [11]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [12]:
df.columns

Index(['Coluna 1', 'Coluna 2', 'Coluna 3'], dtype='object')

In [13]:
df[df['Coluna 1'] > df['Coluna 2']]

    Coluna 1  Coluna 2  Coluna 3
4          8         3         9
6          5         4         5
7          7         2         2
9          8         1         1
13         8         1         2
14         9         2         9
16         7         2         5
18         6         2         6
19         8         3         1

In [14]:
(df['Coluna 1'] > df['Coluna 2']).empty

False

In [15]:
(df[df['Coluna 1']>11]).empty

True

In [16]:
df1 = df.copy()

In [17]:
%%timeit
(df1 == df).all().all()

1.22 ms ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [18]:
%%timeit
df1.equals(df)

73.6 µs ± 7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [19]:
df.head()

   Coluna 1  Coluna 2  Coluna 3
0         7         7         7
1         1         7         2
2         6         8         1
3         0         9         3
4         8         3         9

In [20]:
def multiplica(a,x=2):
    return a*x

In [21]:
df.apply(multiplica)

    Coluna 1  Coluna 2  Coluna 3
0         14        14        14
1          2        14         4
2         12        16         2
3          0        18         6
4         16         6        18
5         18        18         2
6         10         8        10
7         14         4         4
8          6         8         2
9         16         2         2
10         4        14         6
11         6        12         8
12         4        16         0
13        16         2         4
14        18         4        18
15        12        16         0
16        14         4        10
17         4         4        12
18        12         4        12
19        16         6         2

#  <a name="secao_3"> Seção 3 - Indexação </a>
[Voltar ao índice](#indice)

In [22]:
df.head()

   Coluna 1  Coluna 2  Coluna 3
0         7         7         7
1         1         7         2
2         6         8         1
3         0         9         3
4         8         3         9

In [23]:
df.loc[2:5,['Coluna 1','Coluna 3']]

   Coluna 1  Coluna 3
2         6         1
3         0         3
4         8         9
5         9         1

In [24]:
dados = [randint(10,size=3) for a in range(4)]

df = pd.DataFrame(dados,columns=['Coluna 1','Coluna 2','Coluna 3'],index=['a','b','c','d'])

In [25]:
df

   Coluna 1  Coluna 2  Coluna 3
a         5         4         8
b         8         1         5
c         9         8         8
d         7         3         4

In [26]:
df.loc['b','Coluna 2']

1

In [27]:
df.iloc[1]['Coluna 2']

1

In [28]:
df['Coluna 2'].iloc[1]

1

In [29]:
df['Coluna 2']

a    4
b    1
c    8
d    3
Name: Coluna 2, dtype: int64

In [30]:
df = pd.DataFrame(dados,columns=['Coluna 1','Coluna 2','Coluna 3'],index=['2021-2-1','2021-3-1','2021-4-1','2021-5-1'])

In [31]:
df

          Coluna 1  Coluna 2  Coluna 3
2021-2-1         5         4         8
2021-3-1         8         1         5
2021-4-1         9         8         8
2021-5-1         7         3         4

In [32]:
df.loc['2021-3-1']

Coluna 1    8
Coluna 2    1
Coluna 3    5
Name: 2021-3-1, dtype: int64

In [33]:
type(df.index[0])

str

#  <a name="secao_4"> Seção 4  - Leitura e Escrita em arquivos</a>
[Voltar ao índice](#indice)

In [34]:
atletas = pd.read_excel('./archive/Athletes.xlsx')

In [35]:
medalhas = pd.read_excel('./archive/Medals.xlsx')

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [36]:
medalhas[medalhas['Team/NOC']=='Brazil']

    Rank Team/NOC  Gold  Silver  Bronze  Total  Rank by Total
11    12   Brazil     7       6       8     21             12

In [37]:
medalhas[medalhas['Silver']>5]

,Rank,Team/NOC,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
2,3,Japan,27,14,17,58,5
3,4,Great Britain,22,21,22,65,4
4,5,ROC,20,28,23,71,3
5,6,Australia,17,7,22,46,6
6,7,Netherlands,10,12,14,36,9
7,8,France,10,12,11,33,10
8,9,Germany,10,11,16,37,8
9,10,Italy,10,10,20,40,7
10,11,Canada,7,6,11,24,11
11,12,Brazil,7,6,8,21,12
12,13,New Zealand,7,6,7,20,13
14,15,Hungary,6,7,7,20,13
21,22,Spain,3,8,6,17,17
22,23,Sweden,3,6,0,9,26
43,44,Ukraine,1,6,12,19,16

In [39]:
df_cinquenta = medalhas[medalhas['Total']>50]

In [40]:
df_cinquenta.to_csv('.\outputs\ciquenta_medalhes.csv')

In [43]:
df_cinquenta.to_excel('.\outputs\ciquenta_medalhes.xlsx', index=False)

In [44]:
dir(df_cinquenta)

['Bronze',
 'Gold',
 'Rank',
 'Silver',
 'T',
 'Total',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_align_frame',
 '_align_series',
 '_arith_method',
 '_attrs',
 '_box_col_values',
 '_builtin_table',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_cython_table',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_item_cache',
 '_iter_column_arrays',
 '_ix',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

#  <a name="secao_5"> Seção 5 - Algumas Dicas </a>
[Voltar ao índice](#indice)

### NUNCA FAÇA FOR EM PANDAS!

In [47]:
%%timeit
for i in range(len(medalhas)):
    if medalhas.iloc[i]['Gold']>15:
        print('Mais do que 15 medalhas de ouro!')

Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!

Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
297 ms ± 20.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [48]:
%%timeit

for index,row in medalhas.iterrows():
    if row['Gold']>15:
        print('Mais do que 15 medalhas de ouro!')

Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!

Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
Mais do que 15 medalhas de ouro!
97.2 ms ± 48.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [49]:
%%timeit
medalhas[medalhas['Gold']>50]

2.87 ms ± 371 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [50]:
%%timeit
medalhas.query('Gold > 50')

16.1 ms ± 3.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [52]:
medalhas.describe()

            Rank       Gold     Silver     Bronze       Total  Rank by Total
count  93.000000  93.000000  93.000000  93.000000   93.000000      93.000000
mean   46.333333   3.655914   3.634409   4.322581   11.612903      43.494624
std    26.219116   7.022471   6.626339   6.210372   19.091332      24.171769
min     1.000000   0.000000   0.000000   0.000000    1.000000       1.000000
25%    24.000000   0.000000   0.000000   1.000000    2.000000      23.000000
50%    46.000000   1.000000   1.000000   2.000000    4.000000      47.000000
75%    70.000000   3.000000   4.000000   5.000000   11.000000      66.000000
max    86.000000  39.000000  41.000000  33.000000  113.000000      77.000000

In [53]:
pd.crosstab(medalhas['Gold'],medalhas['Silver'])

Silver  0   1   2   3   4   5   6   7   8   10  11  12  14  21  28  32  41
Gold
0       11  12   2   2   1   0   0   0   0   0   0   0   0   0   0   0   0
1        7   6   5   3   0   0   1   0   0   0   0   0   0   0   0   0   0
2        5   3   1   0   1   1   0   0   0   0   0   0   0   0   0   0   0
3        1   4   1   1   2   0   1   0   1   0   0   0   0   0   0   0   0
4        0   1   1   0   2   1   0   0   0   0   0   0   0   0   0   0   0
6        0   0   0   0   1   0   0   1   0   0   0   0   0   0   0   0   0
7        0   0   0   1   0   0   3   0   0   0   0   0   0   0   0   0   0
10       0   0   0   0   0   0   0   0   0   1   1   2   0   0   0   0   0
17       0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0
20       0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
22       0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
27       0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0
38       0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0
39       0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1

#  <a name="conclusao"> Conclusão </a>
[Voltar ao índice](#indice)

Vimos como usar a biblioteca pandas para a manipulação de dados. A pandas é relativamente rápida e tem várias funcionalidades que aceleram o desenvolvimento